services:
  - type: web
    name: bmviewgb-backend
    env: python
    buildCommand: pip install -r requirements.txt && python backend/manage.py collectstatic --noinput
    startCommand: cd backend && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        value: sqlite:///db.sqlite3

  - type: web
    name: bmviewgb-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: bmviewgb-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL