import requests
import pandas as pd
import datetime as dt
import time
import os
from pandas import json_normalize
from tqdm import tqdm
from collections import defaultdict

"""
This script is used to add the system_operator_flag column to the processed CSV files generated by the create_boa_datasets.py script.
This is done by fetching the soFlag data from the BOALF streaming endpoint.
The system_operator_flag column is added to the processed CSV files in the same directory as the script, not as a new file.
"""

API_BASE = "https://data.elexon.co.uk/bmrs/api/v1/datasets"
SESSION = requests.Session()
SESSION.headers.update({"accept": "application/json"})

def _get_boalf_stream(url: str, n_try: int = 3, delay: float = 0.5):
    """Get data from BOALF streaming endpoint with retry logic."""
    for i in range(n_try):
        try:
            r = SESSION.get(url, timeout=60)
            if r.ok:
                j = r.json()
                return j["data"] if isinstance(j, dict) and "data" in j else j
            time.sleep(delay * (i + 1))
        except Exception as e:
            print(f"Attempt {i + 1} failed: {e}")
            if i < n_try - 1:
                time.sleep(delay * (i + 1))
            else:
                raise
    r.raise_for_status()

def fetch_boalf_soflags_for_period(start_date: str, end_date: str):
    """
    Fetch soFlag data for a specific period using BOALF streaming endpoint.
    Returns a dictionary mapping (nationalGridBmUnit, acceptanceNumber) -> soFlag
    """
    print(f"Fetching BOALF data from {start_date} to {end_date}")
    
    # Convert dates to the required format for the API
    start_dt = dt.datetime.fromisoformat(start_date)
    end_dt = dt.datetime.fromisoformat(end_date)
    
    # Format timestamps for API (UTC)
    t_from = start_dt.strftime("%Y-%m-%dT00:00Z")
    t_to = end_dt.strftime("%Y-%m-%dT23:59Z")
    
    url = f"{API_BASE}/BOALF/stream?from={t_from}&to={t_to}"
    
    try:
        data = _get_boalf_stream(url)
        
        if not data:
            print(f"No data returned for period {start_date} to {end_date}")
            return {}
        
        # Convert to DataFrame for easier processing
        df = pd.DataFrame(data)
        
        if df.empty:
            print(f"Empty dataframe for period {start_date} to {end_date}")
            return {}
        
        print(f"Retrieved {len(df)} BOALF records")
        
        # Create mapping from the data
        soFlag_mapping = {}
        for _, row in df.iterrows():
            key = (row['nationalGridBmUnit'], row['acceptanceNumber'])
            soFlag_mapping[key] = row['soFlag']
        
        print(f"Created {len(soFlag_mapping)} soFlag mappings")
        return soFlag_mapping
        
    except Exception as e:
        print(f"Error fetching BOALF data for {start_date} to {end_date}: {e}")
        return {}

def get_soflag_mapping_for_year(year: int, latest_date_2025: str = None):
    """
    Get complete soFlag mapping for a given year using 20-day chunks.
    For 2025, use latest_date_2025 to limit the end date.
    """
    print(f"\n{'='*60}")
    print(f"Building soFlag mapping for {year}")
    print(f"{'='*60}")
    
    # Define year boundaries with lookback/lookahead
    if year == 2025 and latest_date_2025:
        # For 2025, use the latest date in the dataset plus one day
        start_date = dt.date(2024, 12, 31)  # One day lookback into 2024
        end_date = dt.datetime.strptime(latest_date_2025, '%Y-%m-%d').date() + dt.timedelta(days=1)
        print(f"2025 special case: using latest date {latest_date_2025}, end date: {end_date}")
    else:
        # Regular full year with lookback/lookahead
        start_date = dt.date(year - 1, 12, 31)  # One day lookback
        end_date = dt.date(year + 1, 1, 1)      # One day lookahead
    
    master_mapping = {}
    current_date = start_date
    chunk_size = 20  # 20-day chunks
    
    while current_date < end_date:
        chunk_end = min(current_date + dt.timedelta(days=chunk_size - 1), end_date)
        
        print(f"Processing chunk: {current_date} to {chunk_end}")
        
        chunk_mapping = fetch_boalf_soflags_for_period(
            current_date.isoformat(), 
            chunk_end.isoformat()
        )
        
        master_mapping.update(chunk_mapping)
        current_date = chunk_end + dt.timedelta(days=1)
        
        # Small delay between chunks to be respectful to the API
        time.sleep(0.5)
    
    print(f"\nCompleted {year} mapping: {len(master_mapping)} total soFlag entries")
    return master_mapping

def apply_soflag_mapping_to_csv(csv_file: str, soflag_mapping: dict):
    """
    Apply soFlag mapping to a processed CSV file and add system_operator_flag column.
    """
    print(f"\nApplying soFlag mapping to {csv_file}")
    
    if not os.path.exists(csv_file):
        print(f"File {csv_file} not found!")
        return False
    
    # Read the CSV
    df = pd.read_csv(csv_file)
    print(f"Loaded {csv_file}: {df.shape[0]} rows, {df.shape[1]} columns")
    
    # Check if system_operator_flag already exists
    if 'system_operator_flag' in df.columns:
        print(f"system_operator_flag column already exists in {csv_file}")
        flag_counts = df['system_operator_flag'].value_counts()
        print(f"Current distribution - Energy Actions (0): {flag_counts.get(0, 0)}, System Actions (1): {flag_counts.get(1, 0)}")
        return True
    
    # Initialize the system_operator_flag column
    df['system_operator_flag'] = 0  # Default to 0 (Energy Action)
    
    # Apply the mapping
    mapped_count = 0
    missing_count = 0
    
    for idx, row in tqdm(df.iterrows(), total=len(df), desc="Applying soFlag mapping"):
        key = (row['national_grid_bm_unit'], row['acceptance_id'])
        
        if key in soflag_mapping:
            df.at[idx, 'system_operator_flag'] = 1 if soflag_mapping[key] else 0
            mapped_count += 1
        else:
            # Keep default value of 0
            missing_count += 1
    
    print(f"Mapping results:")
    print(f"  Successfully mapped: {mapped_count}")
    print(f"  Missing mappings: {missing_count}")
    print(f"  Coverage: {(mapped_count / len(df)) * 100:.1f}%")
    
    # Show final distribution
    flag_counts = df['system_operator_flag'].value_counts()
    print(f"  Energy Actions (0): {flag_counts.get(0, 0)}")
    print(f"  System Actions (1): {flag_counts.get(1, 0)}")
    
    # Save the updated dataframe
    df.to_csv(csv_file, index=False)
    print(f"Successfully updated and saved {csv_file}")
    
    return True

print("BOALF streaming functions defined successfully!")

def find_latest_date_in_2025_dataset():
    """Find the latest settlement date in the 2025 processed dataset."""
    try:
        df_2025 = pd.read_csv('2025boadf_processed.csv')
        # Convert settlement_date to datetime if it's not already
        df_2025['settlement_date'] = pd.to_datetime(df_2025['settlement_date'])
        latest_date = df_2025['settlement_date'].max().strftime('%Y-%m-%d')
        print(f"Latest date in 2025 dataset: {latest_date}")
        return latest_date
    except Exception as e:
        print(f"Error finding latest date in 2025 dataset: {e}")
        return "2025-06-01"  # Fallback date

def process_all_csvs_with_boalf_streaming():
    """
    Main function to process all CSV files using BOALF streaming approach.
    """
    print("Starting BOALF streaming approach for adding system_operator_flag...")
    print("This approach processes the years in 20-day chunks, which is the date range for the streaming endpoint")
    
    # Define CSV files and their corresponding years
    csv_files = {
        '2021boadf_processed.csv': 2021,
        '2022boadf_processed.csv': 2022,
        '2023boadf_processed.csv': 2023,
        '2024boadf_processed.csv': 2024,
        '2025boadf_processed.csv': 2025
    }
    
    # Find latest date for 2025 dataset
    latest_date_2025 = find_latest_date_in_2025_dataset()
    
    for csv_file, year in csv_files.items():
        if not os.path.exists(csv_file):
            print(f"\\nSkipping {csv_file} - file not found")
            continue
            
        print(f"\\n{'='*80}")
        print(f"PROCESSING {csv_file} (Year: {year})")
        print(f"{'='*80}")
        
        try:
            # Get soFlag mapping for the year
            if year == 2025:
                soflag_mapping = get_soflag_mapping_for_year(year, latest_date_2025)
            else:
                soflag_mapping = get_soflag_mapping_for_year(year)
            
            if not soflag_mapping:
                print(f"No soFlag mapping obtained for {year}, skipping {csv_file}")
                continue
            
            # Apply the mapping to the CSV file
            success = apply_soflag_mapping_to_csv(csv_file, soflag_mapping)
            
            if success:
                print(f"Successfully processed {csv_file}")
            else:
                print(f"Failed to process {csv_file}")
                
        except Exception as e:
            print(f"Error processing {csv_file}: {e}")
            import traceback
            traceback.print_exc()
    
    print(f"\\n{'='*80}")
    print("BOALF streaming processing complete!")
    print(f"{'='*80}")

# Test function to process just one year
def test_single_year(year: int):
    """Test the BOALF streaming approach with a single year."""
    csv_file = f'{year}boadf_processed.csv'
    
    if not os.path.exists(csv_file):
        print(f"File {csv_file} not found!")
        return
    
    print(f"Testing BOALF streaming approach for {year}")
    
    # Special handling for 2025
    if year == 2025:
        latest_date_2025 = find_latest_date_in_2025_dataset()
        soflag_mapping = get_soflag_mapping_for_year(year, latest_date_2025)
    else:
        soflag_mapping = get_soflag_mapping_for_year(year)
    
    if soflag_mapping:
        apply_soflag_mapping_to_csv(csv_file, soflag_mapping)
    else:
        print(f"Failed to get soFlag mapping for {year}")

# Run the function to process all CSV files
process_all_csvs_with_boalf_streaming()
# this function runs the following helper functions defined above in the order:
# 1. _get_boalf_stream()
# 2. fetch_boalf_soflags_for_period()
# 3. get_soflag_mapping_for_year()
# 4. apply_soflag_mapping_to_csv()
# 5. find_latest_date_in_2025_dataset()
# 6. process_all_csvs_with_boalf_streaming()



