import requests
import re
import pandas as pd
import datetime as dt
import time
import os
from pandas import json_normalize
from tqdm import tqdm
from collections import defaultdict

"""
This script is used to add fuel type information to the processed CSV files generated by the create_boa_datasets.py script.
This script uses data from the elexon bmunits endpoint as a primary source of fuel type information, however this source
has a lot of missing data, so we use the skip rates datasets published by NESO at https://www.neso.energy/data-portal/skip-rates
as a fallback source of fuel type information since they contain fuel type information for most BMUs. 
The specific naming of the files to download from NESO is "Skip Rate - In Merit All Balancing Mechanism..." and these files are
referred to as bm_skips_files throughout this script.
The fuel type information is added to the processed CSV files in the same directory as the script, not as a new file so ensure
that the script is run after the create_boa_datasets.py script has created the processed CSV files in the same directory.
"""

# Combined functions to add fuel type information using Elexon df (primary) and bm_skips datasets (fallback)
def load_bm_skips_fuel_mapping():
    """
    Load all bm_skips CSV files and create a comprehensive fuel type mapping.
    """
    print("Loading bm_skips datasets for fallback fuel type information...")
    
    # List all bm_skips files
    bm_skips_files = [
        'bm_skips_12_2024.csv',
        'bm_skips_01_2025.csv', 
        'bm_skips_02_2025.csv',
        'bm_skips_03_2025.csv',
        'bm_skips_04_2025.csv',
        'bm_skips_05_2025.csv',
        'bm_skips_06_2025.csv'
    ]
    
    # Combine all bm_skips data
    all_skips_data = []
    
    for file in bm_skips_files:
        if os.path.exists(file):
            print(f"  Loading {file}...")
            try:
                df_skip = pd.read_csv(file)
                print(f"    Loaded {len(df_skip)} rows")
                all_skips_data.append(df_skip[['bm_unit', 'fuel']].copy())
            except Exception as e:
                print(f"    Error loading {file}: {e}")
        else:
            print(f"  File {file} not found, skipping...")
    
    if not all_skips_data:
        print("No bm_skips files found!")
        return {}
    
    # Combine all data
    combined_skips = pd.concat(all_skips_data, ignore_index=True)
    print(f"Combined bm_skips data: {len(combined_skips)} total rows")
    
    # Remove rows with missing fuel information
    combined_skips = combined_skips.dropna(subset=['fuel'])
    combined_skips = combined_skips[combined_skips['fuel'] != '']
    print(f"After removing missing fuel data: {len(combined_skips)} rows")
    
    # Create fuel type mapping - use the most common fuel type for each BMU
    # This handles cases where a BMU might have different fuel types across time
    bmu_fuel_mapping = (combined_skips.groupby('bm_unit')['fuel']
                       .agg(lambda x: x.mode().iloc[0] if len(x.mode()) > 0 else x.iloc[0])
                       .to_dict())
    
    print(f"Created bm_skips fuel mapping with {len(bmu_fuel_mapping)} unique BMUs")
    
    # Show fuel type distribution in bm_skips data
    fuel_dist = pd.Series(list(bmu_fuel_mapping.values())).value_counts()
    print("Fuel type distribution in bm_skips data:")
    print(fuel_dist.head(10))
    
    return bmu_fuel_mapping

def create_elexon_fuel_mapping(df):
    """
    Create fuel type mapping from Elexon dataframe.
    """
    print("Creating fuel type mapping from Elexon dataframe...")
    
    # Create mapping using nationalGridBmUnit as primary key
    elexon_fuel_mapping = df.set_index('nationalGridBmUnit')['fuelType'].to_dict()
    
    # Also create mapping using elexonBmUnit as key for additional coverage
    elexon_bm_unit_mapping = df.set_index('elexonBmUnit')['fuelType'].to_dict()
    elexon_fuel_mapping.update(elexon_bm_unit_mapping)
    
    print(f"Created Elexon fuel type mapping with {len(elexon_fuel_mapping)} entries")
    
    # Show fuel type distribution in Elexon data
    elexon_fuel_dist = pd.Series(list(elexon_fuel_mapping.values())).value_counts(dropna=False)
    print("Fuel types available in Elexon data:")
    print(elexon_fuel_dist.head(10))
    
    return elexon_fuel_mapping

def add_combined_fuel_type_to_csv(csv_file: str, elexon_fuel_mapping: dict, bm_skips_fuel_mapping: dict):
    """
    Add bmu_fuel_type column using Elexon data (primary) and bm_skips data (fallback).
    Process: Read CSV -> Delete existing bmu_fuel_type -> Add new column -> Fill from Elexon -> Fill gaps from bm_skips
    """
    print(f"\nAdding combined fuel type information to {csv_file}")
    
    if not os.path.exists(csv_file):
        print(f"File {csv_file} not found!")
        return False
    
    # Step 1: Read the CSV
    df_csv = pd.read_csv(csv_file)
    print(f"Loaded {csv_file}: {df_csv.shape[0]} rows, {df_csv.shape[1]} columns")
    
    # Step 2: Delete existing bmu_fuel_type column if it exists to 
    # tally the number of rows that are mapped from Elexon versus bm_skips
    if 'bmu_fuel_type' in df_csv.columns:
        df_csv = df_csv.drop('bmu_fuel_type', axis=1)
        print("Deleted existing bmu_fuel_type column")
    
    # Step 3: Add new bmu_fuel_type column
    print("Adding new bmu_fuel_type column...")
    df_csv['bmu_fuel_type'] = None
    
    # Step 4: Fill values from Elexon dataframe
    print("Step 4: Filling values from Elexon dataframe...")
    
    # Try different BMU column names that might exist in the CSV for Elexon mapping
    elexon_mapped_count = 0
    bmu_columns_for_elexon = ['national_grid_bm_unit', 'bm_unit', 'elexon_bm_unit']
    
    for col_name in bmu_columns_for_elexon:
        if col_name in df_csv.columns:
            print(f"  Trying to map using column: {col_name}")
            
            # Map fuel types for rows that don't have them yet
            mask_missing = df_csv['bmu_fuel_type'].isna()
            if mask_missing.sum() > 0:
                before_count = (~df_csv['bmu_fuel_type'].isna()).sum()
                df_csv.loc[mask_missing, 'bmu_fuel_type'] = df_csv.loc[mask_missing, col_name].map(elexon_fuel_mapping)
                after_count = (~df_csv['bmu_fuel_type'].isna()).sum()
                new_mapped = after_count - before_count
                elexon_mapped_count += new_mapped
                print(f"    Mapped {new_mapped} rows using {col_name} from Elexon data")
            else:
                print(f"    All rows already mapped, skipping {col_name}")
        else:
            print(f"  Column {col_name} not found in CSV")
    
    print(f"Total mapped from Elexon data: {elexon_mapped_count}")
    
    # Step 5: Fill remaining gaps from bm_skips dataset (where value is None, NaN, or 'OTHER')
    print("Step 5: Filling gaps from bm_skips dataset...")
    
    # Define conditions for fallback mapping
    mask_needs_fallback = (
        df_csv['bmu_fuel_type'].isna() | 
        (df_csv['bmu_fuel_type'] == 'OTHER')
    )
    
    print(f"  Rows needing fallback mapping: {mask_needs_fallback.sum()}")
    
    bm_skips_mapped_count = 0
    bmu_columns_for_bm_skips = ['bm_unit', 'national_grid_bm_unit', 'elexon_bm_unit']
    
    for col_name in bmu_columns_for_bm_skips:
        if col_name in df_csv.columns:
            print(f"  Trying fallback mapping using column: {col_name}")
            
            # Only map for rows that still need fallback
            current_mask = (
                df_csv['bmu_fuel_type'].isna() | 
                (df_csv['bmu_fuel_type'] == 'OTHER')
            )
            
            if current_mask.sum() > 0:
                before_count = current_mask.sum()
                
                # Get potential mappings from bm_skips
                potential_mappings = df_csv.loc[current_mask, col_name].map(bm_skips_fuel_mapping)
                
                # Only update if we have a valid mapping (not (None or "OTHER" or NaN))
                valid_mappings_mask = current_mask & potential_mappings.notna() & (potential_mappings != 'OTHER')
                
                if valid_mappings_mask.sum() > 0:
                    df_csv.loc[valid_mappings_mask, 'bmu_fuel_type'] = potential_mappings.loc[valid_mappings_mask]
                    mapped_this_round = valid_mappings_mask.sum()
                    bm_skips_mapped_count += mapped_this_round
                    print(f"    Mapped {mapped_this_round} rows using {col_name} from bm_skips data")
                else:
                    print(f"    No valid mappings found using {col_name}")
            else:
                print(f"    No rows need fallback mapping, skipping {col_name}")
        else:
            print(f"  Column {col_name} not found in CSV")
    
    print(f"Total mapped from bm_skips data: {bm_skips_mapped_count}")
    
    # Step 6: Final cleanup - set any remaining None/NaN to "OTHER"
    # this is a temporary fix to ensure that all rows have a fuel type
    # todo: implement a more elegant solution with some sort of
    # missing from datasets type versus says 'other' in datasets
    final_missing_mask = df_csv['bmu_fuel_type'].isna()
    df_csv.loc[final_missing_mask, 'bmu_fuel_type'] = 'OTHER'
    final_other_count = final_missing_mask.sum()
    
    # Summary statistics
    total_rows = len(df_csv)
    
    print(f"\nFinal fuel type mapping results:")
    print(f"  Total rows: {total_rows}")
    print(f"  Mapped from Elexon data: {elexon_mapped_count}")
    print(f"  Mapped from bm_skips data: {bm_skips_mapped_count}")
    print(f"  Set to 'OTHER': {final_other_count}")
    print(f"  Final coverage: 100.0%")
    
    # Show fuel type distribution
    fuel_counts = df_csv['bmu_fuel_type'].value_counts()
    print(f"\nFinal fuel type distribution:")
    print(fuel_counts)
    
    # Quality check
    none_count = df_csv['bmu_fuel_type'].isna().sum()
    print(f"\nQuality check:")
    print(f"  Remaining NaN values: {none_count}")
    print(f"  All rows now have fuel type classification!")
    
    # Save the updated CSV
    df_csv.to_csv(csv_file, index=False)
    print(f"Updated {csv_file} with combined fuel type information")
    
    return True

def process_all_csvs_with_combined_fuel_types(df):
    """
    Process all CSV files to add fuel type information using Elexon df (primary) and bm_skips (fallback).
    
    Args:
        df: Elexon dataframe with columns 'nationalGridBmUnit', 'elexonBmUnit', 'fuelType'
    """
    print("="*80)
    print("ADDING COMBINED FUEL TYPE INFORMATION TO ALL PROCESSED CSV FILES")
    print("Primary source: Elexon dataframe | Fallback source: bm_skips datasets")
    print("="*80)
    
    # Step 1: Create fuel type mapping from Elexon dataframe
    print("Step 1: Creating fuel type mapping from Elexon dataframe...")
    elexon_fuel_mapping = create_elexon_fuel_mapping(df)
    
    # Step 2: Load bm_skips fuel type mapping
    print(f"\nStep 2: Loading bm_skips fuel type mapping...")
    bm_skips_fuel_mapping = load_bm_skips_fuel_mapping()
    
    if not bm_skips_fuel_mapping:
        print("!!No bm_skips mapping available - will use Elexon data only")
        bm_skips_fuel_mapping = {}
    
    # Step 3: Process each CSV file
    print(f"\nStep 3: Processing CSV files with combined fuel type mapping...")
    csv_files = [
        '2021boadf_processed.csv',
        '2022boadf_processed.csv', 
        '2023boadf_processed.csv',
        '2024boadf_processed.csv',
        '2025boadf_processed.csv'
    ]
    
    for csv_file in csv_files:
        if not os.path.exists(csv_file):
            print(f"\nSkipping {csv_file} - file not found")
            continue
            
        print(f"\n{'='*80}")
        print(f"PROCESSING {csv_file}")
        print(f"{'='*80}")
        
        try:
            success = add_combined_fuel_type_to_csv(csv_file, elexon_fuel_mapping, bm_skips_fuel_mapping)
            
            if success:
                print(f"Successfully processed {csv_file}")
            else:
                print(f"Failed to process {csv_file}")
                
        except Exception as e:
            print(f"Error processing {csv_file}: {e}")
            import traceback
            traceback.print_exc()
    
    print(f"\n{'='*80}")
    print("COMBINED FUEL TYPE PROCESSING COMPLETE")
    print("All CSV files now have comprehensive fuel type information!")
    print("="*80)

def test_combined_fuel_type_single_csv(csv_file: str, df):
    """
    Test combined fuel type addition on a single CSV file.
    
    Args:
        csv_file: Path to CSV file to process
        df: Elexon dataframe with fuel type information
    """
    print(f"Testing combined fuel type addition on {csv_file}")
    
    # Create mappings
    elexon_fuel_mapping = create_elexon_fuel_mapping(df)
    bm_skips_fuel_mapping = load_bm_skips_fuel_mapping()
    
    if not bm_skips_fuel_mapping:
        print("!!!No bm_skips mapping available - will use Elexon data only")
        bm_skips_fuel_mapping = {}
    
    # Process the file
    add_combined_fuel_type_to_csv(csv_file, elexon_fuel_mapping, bm_skips_fuel_mapping)

def analyze_combined_coverage(csv_file: str, df):
    """
    Analyze how many BMUs in a CSV file can be mapped to fuel types using both sources.
    
    Args:
        csv_file: Path to CSV file to analyze
        df: Elexon dataframe with fuel type information
    """
    print(f"Analyzing combined BMU coverage for {csv_file}")
    
    if not os.path.exists(csv_file):
        print(f"File {csv_file} not found!")
        return
    
    # Create mappings
    elexon_fuel_mapping = create_elexon_fuel_mapping(df)
    bm_skips_fuel_mapping = load_bm_skips_fuel_mapping()
    
    # Load CSV
    df_csv = pd.read_csv(csv_file)
    print(f"Loaded {csv_file}: {len(df_csv)} rows")
    
    # Check different BMU columns
    bmu_columns_to_check = ['bm_unit', 'national_grid_bm_unit', 'elexon_bm_unit']
    
    for col_name in bmu_columns_to_check:
        if col_name in df_csv.columns:
            unique_bmus = df_csv[col_name].dropna().unique()
            elexon_mappable = [bmu for bmu in unique_bmus if bmu in elexon_fuel_mapping]
            bm_skips_mappable = [bmu for bmu in unique_bmus if bmu in bm_skips_fuel_mapping]
            combined_mappable = list(set(elexon_mappable + bm_skips_mappable))
            
            print(f"\nColumn: {col_name}")
            print(f"  Unique BMUs: {len(unique_bmus)}")
            print(f"  Elexon mappable: {len(elexon_mappable)} ({len(elexon_mappable)/len(unique_bmus)*100:.1f}%)")
            print(f"  BM skips mappable: {len(bm_skips_mappable)} ({len(bm_skips_mappable)/len(unique_bmus)*100:.1f}%)")
            print(f"  Combined mappable: {len(combined_mappable)} ({len(combined_mappable)/len(unique_bmus)*100:.1f}%)")
            
            # Show some examples of unmappable BMUs
            unmappable = [bmu for bmu in unique_bmus if bmu not in combined_mappable]
            if unmappable:
                print(f"  Examples of unmappable BMUs: {unmappable[:5]}")

print("Combined Elexon + BM Skips fuel type functions defined successfully!")
print("\nTo use:")
print("- Run process_all_csvs_with_combined_fuel_types(df) to add fuel types to all CSVs")
print("- Run test_combined_fuel_type_single_csv('2024boadf_processed.csv', df) to test on one file")
print("- Run analyze_combined_coverage('2024boadf_processed.csv', df) to check mapping coverage")
print("\nNote: 'df' should be your Elexon dataframe with columns 'nationalGridBmUnit', 'elexonBmUnit', 'fuelType'")

# ---------------------------------------------------------------------
# Pull the bmunits data from the Elexon BSC Insights Solution API
# Forms the core of our BMU dataset (copied from create_boa_datasets.py)
# ---------------------------------------------------------------------
# Build the request
BASE_URL  = "https://data.elexon.co.uk/bmrs/api/v1"   # Insights Solution base
ENDPOINT  = "/reference/bmunits/all"                  # specific path
URL       = f"{BASE_URL}{ENDPOINT}"

# Ask explicitly for JSON so the response is an array of objects
headers   = {"Accept": "application/json"}

# Call the API
resp = requests.get(URL, headers=headers, timeout=30)
resp.raise_for_status()          # will raise if the call failed

# Parse straight into a DataFrame
bm_units = resp.json()
df       = pd.DataFrame(bm_units)



# Run the function to process all CSV filesand add fuel type data
process_all_csvs_with_combined_fuel_types(df)
# this function runs the following helper functions defined above in the order:
# 1. load_bm_skips_fuel_mapping()
# 2. create_elexon_fuel_mapping(df)
# 3. add_combined_fuel_type_to_csv(csv_file, elexon_fuel_mapping, bm_skips_fuel_mapping)

